# = Hibernate datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oan_management?zeroDateTimeBehavior=convertToNull
    username: root
    password: root98


# = JPA configurations
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

# = Logging configurations
logging:
  level:
    root: WARN
    com.oan: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: INFO

# = Thymeleaf configurations
spring.thymeleaf.cache: false